// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clearEmptyFrame = `-- name: ClearEmptyFrame :exec
UPDATE frames SET status = 'unlabeled', status_by = NULL, status_at = NULL
WHERE id = $1 AND status = 'empty'
`

func (q *Queries) ClearEmptyFrame(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearEmptyFrame, id)
	return err
}

const copyAnnotations = `-- name: CopyAnnotations :many
INSERT INTO annotations (track_id, frame_id, x, y, width, height, source, status, created_by, updated_by)
SELECT a.track_id, $1, a.x, a.y, a.width, a.height, 'human', 'verified', $2::uuid, $2::uuid
FROM annotations a
WHERE a.frame_id = $3
    AND a.status <> 'rejected'
    AND (cardinality($4::bigint[]) = 0 OR a.track_id = ANY($4::bigint[]))
ON CONFLICT (track_id, frame_id) DO NOTHING
RETURNING id, track_id, frame_id, x, y, width, height, source, status, model_version, created_at, updated_at, created_by, updated_by
`

type CopyAnnotationsParams struct {
	ToFrameID   int64     `json:"to_frame_id"`
	UserID      uuid.UUID `json:"user_id"`
	FromFrameID int64     `json:"from_frame_id"`
	TrackIds    []int64   `json:"track_ids"`
}

func (q *Queries) CopyAnnotations(ctx context.Context, arg CopyAnnotationsParams) ([]Annotation, error) {
	rows, err := q.db.Query(ctx, copyAnnotations,
		arg.ToFrameID,
		arg.UserID,
		arg.FromFrameID,
		arg.TrackIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Annotation
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.FrameID,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.Source,
			&i.Status,
			&i.ModelVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFrameAnnotations = `-- name: CountFrameAnnotations :one
SELECT count(*)::int FROM annotations WHERE frame_id = $1 AND status <> 'rejected'
`

func (q *Queries) CountFrameAnnotations(ctx context.Context, frameID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countFrameAnnotations, frameID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countTrackAnnotations = `-- name: CountTrackAnnotations :one
SELECT count(*)::int FROM annotations WHERE track_id = $1
`

func (q *Queries) CountTrackAnnotations(ctx context.Context, trackID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countTrackAnnotations, trackID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createTrack = `-- name: CreateTrack :one
INSERT INTO tracks (clip_id, label_type_id, attributes)
VALUES ($1, $2, $3)
RETURNING id, clip_id, label_type_id, attributes, created_at
`

type CreateTrackParams struct {
	ClipID      int64  `json:"clip_id"`
	LabelTypeID int64  `json:"label_type_id"`
	Attributes  []byte `json:"attributes"`
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, createTrack, arg.ClipID, arg.LabelTypeID, arg.Attributes)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.ClipID,
		&i.LabelTypeID,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAnnotation = `-- name: DeleteAnnotation :execrows
DELETE FROM annotations WHERE track_id = $1 AND frame_id = $2
`

type DeleteAnnotationParams struct {
	TrackID int64 `json:"track_id"`
	FrameID int64 `json:"frame_id"`
}

func (q *Queries) DeleteAnnotation(ctx context.Context, arg DeleteAnnotationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnotation, arg.TrackID, arg.FrameID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTrack = `-- name: DeleteTrack :execrows
DELETE FROM tracks WHERE id = $1
`

func (q *Queries) DeleteTrack(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrack, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFrame = `-- name: GetFrame :one
SELECT id, video_id, clip_id, idx, phash, status, status_by, status_at FROM frames WHERE id = $1
`

func (q *Queries) GetFrame(ctx context.Context, id int64) (Frame, error) {
	row := q.db.QueryRow(ctx, getFrame, id)
	var i Frame
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ClipID,
		&i.Idx,
		&i.Phash,
		&i.Status,
		&i.StatusBy,
		&i.StatusAt,
	)
	return i, err
}

const getTrack = `-- name: GetTrack :one
SELECT id, clip_id, label_type_id, attributes, created_at FROM tracks WHERE id = $1
`

func (q *Queries) GetTrack(ctx context.Context, id int64) (Track, error) {
	row := q.db.QueryRow(ctx, getTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.ClipID,
		&i.LabelTypeID,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const listClipAnnotations = `-- name: ListClipAnnotations :many
SELECT a.id, a.track_id, a.frame_id, a.x, a.y, a.width, a.height, a.source, a.status, a.model_version, a.created_at, a.updated_at, a.created_by, a.updated_by
FROM annotations a
JOIN tracks t ON t.id = a.track_id
WHERE t.clip_id = $1
ORDER BY a.frame_id, a.track_id
`

func (q *Queries) ListClipAnnotations(ctx context.Context, clipID int64) ([]Annotation, error) {
	rows, err := q.db.Query(ctx, listClipAnnotations, clipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Annotation
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.FrameID,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.Source,
			&i.Status,
			&i.ModelVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClipTracks = `-- name: ListClipTracks :many
SELECT id, clip_id, label_type_id, attributes, created_at FROM tracks WHERE clip_id = $1 ORDER BY id
`

func (q *Queries) ListClipTracks(ctx context.Context, clipID int64) ([]Track, error) {
	rows, err := q.db.Query(ctx, listClipTracks, clipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.ClipID,
			&i.LabelTypeID,
			&i.Attributes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFrameStatus = `-- name: SetFrameStatus :one
UPDATE frames SET
    status = $1,
    status_by = CASE
        WHEN $1 = 'unlabeled' THEN NULL
        WHEN status = $1 THEN status_by
        ELSE $2::uuid
    END,
    status_at = CASE
        WHEN $1 = 'unlabeled' THEN NULL
        WHEN status = $1 THEN status_at
        ELSE now()
    END
WHERE id = $3
RETURNING status
`

type SetFrameStatusParams struct {
	Status string    `json:"status"`
	UserID uuid.UUID `json:"user_id"`
	ID     int64     `json:"id"`
}

// Credit stays with whoever first set the current status.
func (q *Queries) SetFrameStatus(ctx context.Context, arg SetFrameStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, setFrameStatus, arg.Status, arg.UserID, arg.ID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const updateTrack = `-- name: UpdateTrack :one
UPDATE tracks SET label_type_id = $2, attributes = $3
WHERE id = $1
RETURNING id, clip_id, label_type_id, attributes, created_at
`

type UpdateTrackParams struct {
	ID          int64  `json:"id"`
	LabelTypeID int64  `json:"label_type_id"`
	Attributes  []byte `json:"attributes"`
}

func (q *Queries) UpdateTrack(ctx context.Context, arg UpdateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, updateTrack, arg.ID, arg.LabelTypeID, arg.Attributes)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.ClipID,
		&i.LabelTypeID,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAnnotation = `-- name: UpsertAnnotation :one
INSERT INTO annotations (track_id, frame_id, x, y, width, height, source, status, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, 'human', 'verified', $7::uuid, $7::uuid)
ON CONFLICT (track_id, frame_id) DO UPDATE SET
    x = excluded.x,
    y = excluded.y,
    width = excluded.width,
    height = excluded.height,
    source = 'human',
    status = 'verified',
    model_version = '',
    updated_by = excluded.updated_by,
    updated_at = now()
RETURNING id, track_id, frame_id, x, y, width, height, source, status, model_version, created_at, updated_at, created_by, updated_by
`

type UpsertAnnotationParams struct {
	TrackID int64     `json:"track_id"`
	FrameID int64     `json:"frame_id"`
	X       float64   `json:"x"`
	Y       float64   `json:"y"`
	Width   float64   `json:"width"`
	Height  float64   `json:"height"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) UpsertAnnotation(ctx context.Context, arg UpsertAnnotationParams) (Annotation, error) {
	row := q.db.QueryRow(ctx, upsertAnnotation,
		arg.TrackID,
		arg.FrameID,
		arg.X,
		arg.Y,
		arg.Width,
		arg.Height,
		arg.UserID,
	)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.FrameID,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.Source,
		&i.Status,
		&i.ModelVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
