// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claims.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimClip = `-- name: ClaimClip :execrows
INSERT INTO clip_claims (clip_id, user_id) VALUES ($1, $2)
ON CONFLICT (clip_id) DO UPDATE SET user_id = excluded.user_id, active_at = now()
WHERE clip_claims.user_id = excluded.user_id OR clip_claims.active_at < $3
`

type ClaimClipParams struct {
	ClipID      int64              `json:"clip_id"`
	UserID      uuid.UUID          `json:"user_id"`
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
}

// Takes the clip unless someone else claimed it and is still active.
func (q *Queries) ClaimClip(ctx context.Context, arg ClaimClipParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimClip, arg.ClipID, arg.UserID, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listClipClaims = `-- name: ListClipClaims :many
SELECT cc.clip_id, cc.active_at, u.id, u.name, u.username, u.email, u.password_hash, u.role, u.slack_user_id, u.disabled, u.created_at, u.last_login_at
FROM clip_claims cc
JOIN users u ON u.id = cc.user_id
WHERE cc.clip_id = ANY($1::bigint[])
`

type ListClipClaimsRow struct {
	ClipID   int64              `json:"clip_id"`
	ActiveAt pgtype.Timestamptz `json:"active_at"`
	User     User               `json:"user"`
}

func (q *Queries) ListClipClaims(ctx context.Context, clipIds []int64) ([]ListClipClaimsRow, error) {
	rows, err := q.db.Query(ctx, listClipClaims, clipIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClipClaimsRow
	for rows.Next() {
		var i ListClipClaimsRow
		if err := rows.Scan(
			&i.ClipID,
			&i.ActiveAt,
			&i.User.ID,
			&i.User.Name,
			&i.User.Username,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.Role,
			&i.User.SlackUserID,
			&i.User.Disabled,
			&i.User.CreatedAt,
			&i.User.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClipProgress = `-- name: ListClipProgress :many
SELECT
    c.id, c.video_id, v.name AS video_name, c.idx, c.frame_count,
    (SELECT count(*) FROM frames f WHERE f.clip_id = c.id AND f.status <> 'unlabeled')::int AS labeled_frame_count
FROM clips c
JOIN videos v ON v.id = c.video_id
WHERE v.status = 'ready'
ORDER BY v.created_at DESC, v.id DESC, c.idx
`

type ListClipProgressRow struct {
	ID                int64  `json:"id"`
	VideoID           int64  `json:"video_id"`
	VideoName         string `json:"video_name"`
	Idx               int32  `json:"idx"`
	FrameCount        int32  `json:"frame_count"`
	LabeledFrameCount int32  `json:"labeled_frame_count"`
}

func (q *Queries) ListClipProgress(ctx context.Context) ([]ListClipProgressRow, error) {
	rows, err := q.db.Query(ctx, listClipProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClipProgressRow
	for rows.Next() {
		var i ListClipProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.VideoName,
			&i.Idx,
			&i.FrameCount,
			&i.LabeledFrameCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenClips = `-- name: ListOpenClips :many
SELECT
    c.id, c.video_id, c.idx, c.start_frame, c.frame_count,
    v.id, v.name, v.filename, v.notes, v.status, v.error, v.ingest_progress, v.split, v.extract_fps, v.width, v.height, v.fps, v.duration_ms, v.frame_count, v.created_at,
    (SELECT count(*) FROM frames f WHERE f.clip_id = c.id AND f.status <> 'unlabeled')::int AS labeled_frame_count,
    (SELECT count(*) FROM annotations a JOIN tracks t ON t.id = a.track_id WHERE t.clip_id = c.id)::int AS box_count
FROM clip_claims cc
JOIN clips c ON c.id = cc.clip_id
JOIN videos v ON v.id = c.video_id
WHERE cc.user_id = $1
    AND v.status = 'ready'
    AND EXISTS (SELECT 1 FROM frames f WHERE f.clip_id = c.id AND f.status = 'unlabeled')
ORDER BY cc.active_at DESC
`

type ListOpenClipsRow struct {
	Clip              Clip  `json:"clip"`
	Video             Video `json:"video"`
	LabeledFrameCount int32 `json:"labeled_frame_count"`
	BoxCount          int32 `json:"box_count"`
}

func (q *Queries) ListOpenClips(ctx context.Context, userID uuid.UUID) ([]ListOpenClipsRow, error) {
	rows, err := q.db.Query(ctx, listOpenClips, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenClipsRow
	for rows.Next() {
		var i ListOpenClipsRow
		if err := rows.Scan(
			&i.Clip.ID,
			&i.Clip.VideoID,
			&i.Clip.Idx,
			&i.Clip.StartFrame,
			&i.Clip.FrameCount,
			&i.Video.ID,
			&i.Video.Name,
			&i.Video.Filename,
			&i.Video.Notes,
			&i.Video.Status,
			&i.Video.Error,
			&i.Video.IngestProgress,
			&i.Video.Split,
			&i.Video.ExtractFps,
			&i.Video.Width,
			&i.Video.Height,
			&i.Video.Fps,
			&i.Video.DurationMs,
			&i.Video.FrameCount,
			&i.Video.CreatedAt,
			&i.LabeledFrameCount,
			&i.BoxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextClip = `-- name: NextClip :one
WITH worked AS (
    SELECT c.video_id, count(*) AS clips
    FROM clips c
    WHERE EXISTS (SELECT 1 FROM clip_claims cc WHERE cc.clip_id = c.id)
        OR EXISTS (SELECT 1 FROM frames f WHERE f.clip_id = c.id AND f.status <> 'unlabeled')
    GROUP BY c.video_id
)
SELECT c.id
FROM clips c
JOIN videos v ON v.id = c.video_id
LEFT JOIN clip_claims cc ON cc.clip_id = c.id
LEFT JOIN worked w ON w.video_id = c.video_id
WHERE v.status = 'ready'
    AND c.id <> $1
    AND (cc.clip_id IS NULL OR cc.active_at < $2)
    AND EXISTS (SELECT 1 FROM frames f WHERE f.clip_id = c.id AND f.status = 'unlabeled')
ORDER BY
    EXISTS (SELECT 1 FROM frames f WHERE f.clip_id = c.id AND f.status <> 'unlabeled') DESC,
    coalesce(w.clips, 0),
    random()
LIMIT 1
FOR UPDATE OF c SKIP LOCKED
`

type NextClipParams struct {
	SkipClipID  int64              `json:"skip_clip_id"`
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
}

// Started clips that were abandoned come first so they get finished. After
// that, clips come from the video with the fewest clips worked on, so labels
// spread across as much footage as possible.
func (q *Queries) NextClip(ctx context.Context, arg NextClipParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextClip, arg.SkipClipID, arg.StaleBefore)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const releaseClipClaim = `-- name: ReleaseClipClaim :exec
DELETE FROM clip_claims WHERE clip_id = $1 AND user_id = $2
`

type ReleaseClipClaimParams struct {
	ClipID int64     `json:"clip_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ReleaseClipClaim(ctx context.Context, arg ReleaseClipClaimParams) error {
	_, err := q.db.Exec(ctx, releaseClipClaim, arg.ClipID, arg.UserID)
	return err
}
