// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clips.sql

package db

import (
	"context"
)

const getClip = `-- name: GetClip :one
SELECT id, video_id, idx, start_frame, frame_count FROM clips WHERE id = $1
`

func (q *Queries) GetClip(ctx context.Context, id int64) (Clip, error) {
	row := q.db.QueryRow(ctx, getClip, id)
	var i Clip
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Idx,
		&i.StartFrame,
		&i.FrameCount,
	)
	return i, err
}

const getClipLabelStats = `-- name: GetClipLabelStats :one
SELECT
    (SELECT count(*) FROM frames f WHERE f.clip_id = $1 AND f.status <> 'unlabeled')::int AS labeled_frame_count,
    (SELECT count(*) FROM annotations a JOIN tracks t ON t.id = a.track_id WHERE t.clip_id = $1)::int AS box_count
`

type GetClipLabelStatsRow struct {
	LabeledFrameCount int32 `json:"labeled_frame_count"`
	BoxCount          int32 `json:"box_count"`
}

func (q *Queries) GetClipLabelStats(ctx context.Context, clipID int64) (GetClipLabelStatsRow, error) {
	row := q.db.QueryRow(ctx, getClipLabelStats, clipID)
	var i GetClipLabelStatsRow
	err := row.Scan(&i.LabeledFrameCount, &i.BoxCount)
	return i, err
}

const getNeighbourClips = `-- name: GetNeighbourClips :one
SELECT
    coalesce((SELECT p.id FROM clips p WHERE p.video_id = c.video_id AND p.idx = c.idx - 1), 0)::bigint AS previous_id,
    coalesce((SELECT n.id FROM clips n WHERE n.video_id = c.video_id AND n.idx = c.idx + 1), 0)::bigint AS next_id
FROM clips c
WHERE c.id = $1
`

type GetNeighbourClipsRow struct {
	PreviousID int64 `json:"previous_id"`
	NextID     int64 `json:"next_id"`
}

func (q *Queries) GetNeighbourClips(ctx context.Context, id int64) (GetNeighbourClipsRow, error) {
	row := q.db.QueryRow(ctx, getNeighbourClips, id)
	var i GetNeighbourClipsRow
	err := row.Scan(&i.PreviousID, &i.NextID)
	return i, err
}

const listClipFrames = `-- name: ListClipFrames :many
SELECT id, video_id, clip_id, idx, phash, status FROM frames WHERE clip_id = $1 ORDER BY idx
`

func (q *Queries) ListClipFrames(ctx context.Context, clipID int64) ([]Frame, error) {
	rows, err := q.db.Query(ctx, listClipFrames, clipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Frame
	for rows.Next() {
		var i Frame
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ClipID,
			&i.Idx,
			&i.Phash,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
