// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertFrames implements pgx.CopyFromSource.
type iteratorForInsertFrames struct {
	rows                 []InsertFramesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertFrames) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertFrames) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].VideoID,
		r.rows[0].ClipID,
		r.rows[0].Idx,
		r.rows[0].Phash,
	}, nil
}

func (r iteratorForInsertFrames) Err() error {
	return nil
}

func (q *Queries) InsertFrames(ctx context.Context, arg []InsertFramesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"frames"}, []string{"video_id", "clip_id", "idx", "phash"}, &iteratorForInsertFrames{rows: arg})
}
