// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gold.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGoldFrame = `-- name: DeleteGoldFrame :exec
DELETE FROM gold_frames WHERE frame_id = $1
`

func (q *Queries) DeleteGoldFrame(ctx context.Context, frameID int64) error {
	_, err := q.db.Exec(ctx, deleteGoldFrame, frameID)
	return err
}

const framesSinceGoldCheck = `-- name: FramesSinceGoldCheck :one
SELECT count(*)::int
FROM frames
WHERE status_by = $1::uuid
    AND status_at > coalesce(
        (SELECT max(created_at) FROM gold_attempts WHERE user_id = $1::uuid),
        '-infinity'::timestamptz
    )
`

func (q *Queries) FramesSinceGoldCheck(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, framesSinceGoldCheck, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getGoldFrame = `-- name: GetGoldFrame :one
SELECT g.frame_id, g.boxes, f.idx, f.video_id, v.width, v.height
FROM gold_frames g
JOIN frames f ON f.id = g.frame_id
JOIN videos v ON v.id = f.video_id
WHERE g.frame_id = $1
`

type GetGoldFrameRow struct {
	FrameID int64  `json:"frame_id"`
	Boxes   []byte `json:"boxes"`
	Idx     int32  `json:"idx"`
	VideoID int64  `json:"video_id"`
	Width   int32  `json:"width"`
	Height  int32  `json:"height"`
}

func (q *Queries) GetGoldFrame(ctx context.Context, frameID int64) (GetGoldFrameRow, error) {
	row := q.db.QueryRow(ctx, getGoldFrame, frameID)
	var i GetGoldFrameRow
	err := row.Scan(
		&i.FrameID,
		&i.Boxes,
		&i.Idx,
		&i.VideoID,
		&i.Width,
		&i.Height,
	)
	return i, err
}

const hasGoldAttempt = `-- name: HasGoldAttempt :one
SELECT EXISTS (SELECT 1 FROM gold_attempts WHERE frame_id = $1 AND user_id = $2)
`

type HasGoldAttemptParams struct {
	FrameID int64     `json:"frame_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) HasGoldAttempt(ctx context.Context, arg HasGoldAttemptParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasGoldAttempt, arg.FrameID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertGoldAttempt = `-- name: InsertGoldAttempt :execrows
INSERT INTO gold_attempts (
    frame_id, user_id, boxes, reference_count, answer_count, matched, correct, iou_sum, score
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (frame_id, user_id) DO NOTHING
`

type InsertGoldAttemptParams struct {
	FrameID        int64     `json:"frame_id"`
	UserID         uuid.UUID `json:"user_id"`
	Boxes          []byte    `json:"boxes"`
	ReferenceCount int32     `json:"reference_count"`
	AnswerCount    int32     `json:"answer_count"`
	Matched        int32     `json:"matched"`
	Correct        int32     `json:"correct"`
	IouSum         float64   `json:"iou_sum"`
	Score          float64   `json:"score"`
}

func (q *Queries) InsertGoldAttempt(ctx context.Context, arg InsertGoldAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertGoldAttempt,
		arg.FrameID,
		arg.UserID,
		arg.Boxes,
		arg.ReferenceCount,
		arg.AnswerCount,
		arg.Matched,
		arg.Correct,
		arg.IouSum,
		arg.Score,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertGoldFrame = `-- name: InsertGoldFrame :exec
INSERT INTO gold_frames (frame_id, boxes, created_by) VALUES ($1, $2, $3::uuid)
ON CONFLICT (frame_id) DO NOTHING
`

type InsertGoldFrameParams struct {
	FrameID   int64     `json:"frame_id"`
	Boxes     []byte    `json:"boxes"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) InsertGoldFrame(ctx context.Context, arg InsertGoldFrameParams) error {
	_, err := q.db.Exec(ctx, insertGoldFrame, arg.FrameID, arg.Boxes, arg.CreatedBy)
	return err
}

const listClipGoldFrames = `-- name: ListClipGoldFrames :many
SELECT g.frame_id
FROM gold_frames g
JOIN frames f ON f.id = g.frame_id
WHERE f.clip_id = $1
`

func (q *Queries) ListClipGoldFrames(ctx context.Context, clipID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listClipGoldFrames, clipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var frame_id int64
		if err := rows.Scan(&frame_id); err != nil {
			return nil, err
		}
		items = append(items, frame_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFrameVerifiedBoxes = `-- name: ListFrameVerifiedBoxes :many
SELECT t.label_type_id, t.attributes, a.x, a.y, a.width, a.height
FROM annotations a
JOIN tracks t ON t.id = a.track_id
WHERE a.frame_id = $1 AND a.status = 'verified'
ORDER BY a.id
`

type ListFrameVerifiedBoxesRow struct {
	LabelTypeID int64   `json:"label_type_id"`
	Attributes  []byte  `json:"attributes"`
	X           float64 `json:"x"`
	Y           float64 `json:"y"`
	Width       float64 `json:"width"`
	Height      float64 `json:"height"`
}

func (q *Queries) ListFrameVerifiedBoxes(ctx context.Context, frameID int64) ([]ListFrameVerifiedBoxesRow, error) {
	rows, err := q.db.Query(ctx, listFrameVerifiedBoxes, frameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFrameVerifiedBoxesRow
	for rows.Next() {
		var i ListFrameVerifiedBoxesRow
		if err := rows.Scan(
			&i.LabelTypeID,
			&i.Attributes,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoldFrames = `-- name: ListGoldFrames :many
SELECT
    g.frame_id, f.clip_id, f.idx, f.video_id, v.name AS video_name,
    jsonb_array_length(g.boxes)::int AS box_count,
    count(ga.user_id)::int AS attempts,
    coalesce(avg(ga.score), 0)::float8 AS mean_score
FROM gold_frames g
JOIN frames f ON f.id = g.frame_id
JOIN videos v ON v.id = f.video_id
LEFT JOIN gold_attempts ga ON ga.frame_id = g.frame_id
GROUP BY g.frame_id, f.id, v.id
ORDER BY g.created_at DESC, g.frame_id DESC
`

type ListGoldFramesRow struct {
	FrameID   int64   `json:"frame_id"`
	ClipID    int64   `json:"clip_id"`
	Idx       int32   `json:"idx"`
	VideoID   int64   `json:"video_id"`
	VideoName string  `json:"video_name"`
	BoxCount  int32   `json:"box_count"`
	Attempts  int32   `json:"attempts"`
	MeanScore float64 `json:"mean_score"`
}

func (q *Queries) ListGoldFrames(ctx context.Context) ([]ListGoldFramesRow, error) {
	rows, err := q.db.Query(ctx, listGoldFrames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoldFramesRow
	for rows.Next() {
		var i ListGoldFramesRow
		if err := rows.Scan(
			&i.FrameID,
			&i.ClipID,
			&i.Idx,
			&i.VideoID,
			&i.VideoName,
			&i.BoxCount,
			&i.Attempts,
			&i.MeanScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoldLabelers = `-- name: ListGoldLabelers :many
SELECT
    u.id, u.name, u.username, u.role, u.created_at,
    count(*)::int AS attempts,
    sum(ga.correct)::bigint AS correct,
    sum(ga.reference_count + ga.answer_count - ga.matched)::bigint AS scored,
    sum(ga.matched)::bigint AS matched,
    sum(ga.iou_sum)::float8 AS iou_sum
FROM gold_attempts ga
JOIN users u ON u.id = ga.user_id
GROUP BY u.id
`

type ListGoldLabelersRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Username  string             `json:"username"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Attempts  int32              `json:"attempts"`
	Correct   int64              `json:"correct"`
	Scored    int64              `json:"scored"`
	Matched   int64              `json:"matched"`
	IouSum    float64            `json:"iou_sum"`
}

func (q *Queries) ListGoldLabelers(ctx context.Context) ([]ListGoldLabelersRow, error) {
	rows, err := q.db.Query(ctx, listGoldLabelers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoldLabelersRow
	for rows.Next() {
		var i ListGoldLabelersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
			&i.Attempts,
			&i.Correct,
			&i.Scored,
			&i.Matched,
			&i.IouSum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextGoldFrame = `-- name: NextGoldFrame :one
SELECT g.frame_id
FROM gold_frames g
JOIN frames f ON f.id = g.frame_id
JOIN videos v ON v.id = f.video_id
WHERE v.status = 'ready'
    AND g.created_by IS DISTINCT FROM $1::uuid
    AND NOT EXISTS (SELECT 1 FROM gold_attempts ga WHERE ga.frame_id = g.frame_id AND ga.user_id = $1::uuid)
    AND NOT EXISTS (SELECT 1 FROM clip_claims cc WHERE cc.clip_id = f.clip_id AND cc.user_id = $1::uuid)
    AND NOT EXISTS (SELECT 1 FROM frames wf WHERE wf.clip_id = f.clip_id AND wf.status_by = $1::uuid)
    AND NOT EXISTS (
        SELECT 1
        FROM annotations a
        JOIN tracks t ON t.id = a.track_id
        WHERE t.clip_id = f.clip_id AND (a.created_by = $1::uuid OR a.updated_by = $1::uuid)
    )
ORDER BY md5(g.frame_id::text || $1::text)
LIMIT 1
`

// Skips gold frames from clips the labeler worked on, since they may remember
// the answer. The order is shuffled per labeler but stable, so skipping a
// check does not hand out an easier one.
func (q *Queries) NextGoldFrame(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextGoldFrame, userID)
	var frame_id int64
	err := row.Scan(&frame_id)
	return frame_id, err
}
