// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package db

import (
	"context"
)

const countTracksForLabelType = `-- name: CountTracksForLabelType :one
SELECT count(*)::int FROM tracks WHERE label_type_id = $1
`

func (q *Queries) CountTracksForLabelType(ctx context.Context, labelTypeID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countTracksForLabelType, labelTypeID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createLabelType = `-- name: CreateLabelType :one
INSERT INTO label_types (name, color, description, attributes, position)
VALUES ($1, $2, $3, $4, (SELECT coalesce(max(position), -1) + 1 FROM label_types))
RETURNING id, name, color, description, position, attributes, created_at
`

type CreateLabelTypeParams struct {
	Name        string `json:"name"`
	Color       string `json:"color"`
	Description string `json:"description"`
	Attributes  []byte `json:"attributes"`
}

func (q *Queries) CreateLabelType(ctx context.Context, arg CreateLabelTypeParams) (LabelType, error) {
	row := q.db.QueryRow(ctx, createLabelType,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.Attributes,
	)
	var i LabelType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.Position,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLabelType = `-- name: DeleteLabelType :execrows
DELETE FROM label_types WHERE id = $1
`

func (q *Queries) DeleteLabelType(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLabelType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLabelType = `-- name: GetLabelType :one
SELECT id, name, color, description, position, attributes, created_at FROM label_types WHERE id = $1
`

func (q *Queries) GetLabelType(ctx context.Context, id int64) (LabelType, error) {
	row := q.db.QueryRow(ctx, getLabelType, id)
	var i LabelType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.Position,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const listLabelTypes = `-- name: ListLabelTypes :many
SELECT
    lt.id, lt.name, lt.color, lt.description, lt.position, lt.attributes, lt.created_at,
    (SELECT count(*) FROM tracks t WHERE t.label_type_id = lt.id)::int AS track_count,
    (SELECT count(*) FROM annotations a JOIN tracks t ON t.id = a.track_id WHERE t.label_type_id = lt.id)::int AS box_count
FROM label_types lt
ORDER BY lt.position, lt.id
`

type ListLabelTypesRow struct {
	LabelType  LabelType `json:"label_type"`
	TrackCount int32     `json:"track_count"`
	BoxCount   int32     `json:"box_count"`
}

func (q *Queries) ListLabelTypes(ctx context.Context) ([]ListLabelTypesRow, error) {
	rows, err := q.db.Query(ctx, listLabelTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLabelTypesRow
	for rows.Next() {
		var i ListLabelTypesRow
		if err := rows.Scan(
			&i.LabelType.ID,
			&i.LabelType.Name,
			&i.LabelType.Color,
			&i.LabelType.Description,
			&i.LabelType.Position,
			&i.LabelType.Attributes,
			&i.LabelType.CreatedAt,
			&i.TrackCount,
			&i.BoxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLabelTypePosition = `-- name: SetLabelTypePosition :exec
UPDATE label_types SET position = $2 WHERE id = $1
`

type SetLabelTypePositionParams struct {
	ID       int64 `json:"id"`
	Position int32 `json:"position"`
}

func (q *Queries) SetLabelTypePosition(ctx context.Context, arg SetLabelTypePositionParams) error {
	_, err := q.db.Exec(ctx, setLabelTypePosition, arg.ID, arg.Position)
	return err
}

const updateLabelType = `-- name: UpdateLabelType :one
UPDATE label_types SET name = $2, color = $3, description = $4, attributes = $5
WHERE id = $1
RETURNING id, name, color, description, position, attributes, created_at
`

type UpdateLabelTypeParams struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Color       string `json:"color"`
	Description string `json:"description"`
	Attributes  []byte `json:"attributes"`
}

func (q *Queries) UpdateLabelType(ctx context.Context, arg UpdateLabelTypeParams) (LabelType, error) {
	row := q.db.QueryRow(ctx, updateLabelType,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.Attributes,
	)
	var i LabelType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.Position,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}
