// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Annotation struct {
	ID           int64              `json:"id"`
	TrackID      int64              `json:"track_id"`
	FrameID      int64              `json:"frame_id"`
	X            float64            `json:"x"`
	Y            float64            `json:"y"`
	Width        float64            `json:"width"`
	Height       float64            `json:"height"`
	Source       string             `json:"source"`
	Status       string             `json:"status"`
	ModelVersion string             `json:"model_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
}

type Clip struct {
	ID         int64 `json:"id"`
	VideoID    int64 `json:"video_id"`
	Idx        int32 `json:"idx"`
	StartFrame int32 `json:"start_frame"`
	FrameCount int32 `json:"frame_count"`
}

type ClipClaim struct {
	ClipID   int64              `json:"clip_id"`
	UserID   uuid.UUID          `json:"user_id"`
	ActiveAt pgtype.Timestamptz `json:"active_at"`
}

type Dataset struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Status     string             `json:"status"`
	Error      string             `json:"error"`
	Progress   float32            `json:"progress"`
	Options    []byte             `json:"options"`
	Stats      []byte             `json:"stats"`
	SizeBytes  int64              `json:"size_bytes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

type Frame struct {
	ID       int64              `json:"id"`
	VideoID  int64              `json:"video_id"`
	ClipID   int64              `json:"clip_id"`
	Idx      int32              `json:"idx"`
	Phash    int64              `json:"phash"`
	Status   string             `json:"status"`
	StatusBy pgtype.UUID        `json:"status_by"`
	StatusAt pgtype.Timestamptz `json:"status_at"`
}

type LabelType struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Color       string             `json:"color"`
	Description string             `json:"description"`
	Position    int32              `json:"position"`
	Attributes  []byte             `json:"attributes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	TokenHash []byte             `json:"token_hash"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Track struct {
	ID          int64              `json:"id"`
	ClipID      int64              `json:"clip_id"`
	LabelTypeID int64              `json:"label_type_id"`
	Attributes  []byte             `json:"attributes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Role         string             `json:"role"`
	SlackUserID  pgtype.Text        `json:"slack_user_id"`
	Disabled     bool               `json:"disabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

type Video struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Filename       string             `json:"filename"`
	Notes          string             `json:"notes"`
	Status         string             `json:"status"`
	Error          string             `json:"error"`
	IngestProgress float32            `json:"ingest_progress"`
	Split          string             `json:"split"`
	ExtractFps     float64            `json:"extract_fps"`
	Width          int32              `json:"width"`
	Height         int32              `json:"height"`
	Fps            float64            `json:"fps"`
	DurationMs     int64              `json:"duration_ms"`
	FrameCount     int32              `json:"frame_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
