// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Clip struct {
	ID         int64 `json:"id"`
	VideoID    int64 `json:"video_id"`
	Idx        int32 `json:"idx"`
	StartFrame int32 `json:"start_frame"`
	FrameCount int32 `json:"frame_count"`
}

type Frame struct {
	ID      int64 `json:"id"`
	VideoID int64 `json:"video_id"`
	ClipID  int64 `json:"clip_id"`
	Idx     int32 `json:"idx"`
	Phash   int64 `json:"phash"`
}

type Video struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Filename       string             `json:"filename"`
	Notes          string             `json:"notes"`
	Status         string             `json:"status"`
	Error          string             `json:"error"`
	IngestProgress float32            `json:"ingest_progress"`
	Split          string             `json:"split"`
	ExtractFps     float64            `json:"extract_fps"`
	Width          int32              `json:"width"`
	Height         int32              `json:"height"`
	Fps            float64            `json:"fps"`
	DurationMs     int64              `json:"duration_ms"`
	FrameCount     int32              `json:"frame_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
