// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountClips(ctx context.Context, videoID int64) (int32, error)
	CreateClip(ctx context.Context, arg CreateClipParams) (int64, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteClips(ctx context.Context, videoID int64) error
	DeleteVideo(ctx context.Context, id int64) (int64, error)
	FailIngest(ctx context.Context, arg FailIngestParams) error
	FailInterruptedIngests(ctx context.Context) (int64, error)
	FinishIngest(ctx context.Context, arg FinishIngestParams) error
	GetVideo(ctx context.Context, id int64) (Video, error)
	InsertFrames(ctx context.Context, arg []InsertFramesParams) (int64, error)
	ListClips(ctx context.Context, videoID int64) ([]Clip, error)
	ListVideos(ctx context.Context) ([]ListVideosRow, error)
	QueueIngest(ctx context.Context, id int64) (Video, error)
	SetIngestProgress(ctx context.Context, arg SetIngestProgressParams) error
	SetVideoProbe(ctx context.Context, arg SetVideoProbeParams) error
	StartProcessing(ctx context.Context, id int64) (int64, error)
	UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error)
}

var _ Querier = (*Queries)(nil)
