// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, name, username, email, password_hash, role, slack_user_id, disabled, created_at, last_login_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.SlackUserID,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const leaderboard = `-- name: Leaderboard :many
WITH contributions AS (
    SELECT created_by AS user_id, 1 AS boxes, 0 AS frames
    FROM annotations
    WHERE created_by IS NOT NULL
        AND ($1::timestamptz IS NULL OR created_at >= $1)
    UNION ALL
    SELECT status_by, 0, 1
    FROM frames
    WHERE status_by IS NOT NULL
        AND ($1::timestamptz IS NULL OR status_at >= $1)
)
SELECT
    u.id, u.name, u.username, u.role, u.created_at,
    sum(c.boxes)::bigint AS boxes,
    sum(c.frames)::bigint AS frames
FROM contributions c
JOIN users u ON u.id = c.user_id
GROUP BY u.id
ORDER BY sum(c.boxes) + sum(c.frames) DESC, sum(c.frames) DESC, u.name
`

type LeaderboardRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Username  string             `json:"username"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Boxes     int64              `json:"boxes"`
	Frames    int64              `json:"frames"`
}

func (q *Queries) Leaderboard(ctx context.Context, since pgtype.Timestamptz) ([]LeaderboardRow, error) {
	rows, err := q.db.Query(ctx, leaderboard, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardRow
	for rows.Next() {
		var i LeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
			&i.Boxes,
			&i.Frames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userClipCount = `-- name: UserClipCount :one
SELECT count(DISTINCT clip_id)::bigint
FROM (
    SELECT t.clip_id
    FROM annotations a
    JOIN tracks t ON t.id = a.track_id
    WHERE a.created_by = $1::uuid
    UNION ALL
    SELECT clip_id FROM frames WHERE status_by = $1::uuid
) c
`

func (q *Queries) UserClipCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, userClipCount, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const userContributionDays = `-- name: UserContributionDays :many
SELECT day::text AS day, count(*)::bigint AS count
FROM (
    SELECT (created_at AT TIME ZONE $1::text)::date AS day
    FROM annotations
    WHERE created_by = $2::uuid
    UNION ALL
    SELECT (status_at AT TIME ZONE $1::text)::date
    FROM frames
    WHERE status_by = $2::uuid
) c
GROUP BY day
ORDER BY day
`

type UserContributionDaysParams struct {
	TimeZone string    `json:"time_zone"`
	UserID   uuid.UUID `json:"user_id"`
}

type UserContributionDaysRow struct {
	Day   string `json:"day"`
	Count int64  `json:"count"`
}

func (q *Queries) UserContributionDays(ctx context.Context, arg UserContributionDaysParams) ([]UserContributionDaysRow, error) {
	rows, err := q.db.Query(ctx, userContributionDays, arg.TimeZone, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserContributionDaysRow
	for rows.Next() {
		var i UserContributionDaysRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userLabelTypeCounts = `-- name: UserLabelTypeCounts :many
SELECT lt.id, lt.name, lt.color, count(*)::bigint AS boxes
FROM annotations a
JOIN tracks t ON t.id = a.track_id
JOIN label_types lt ON lt.id = t.label_type_id
WHERE a.created_by = $1::uuid
GROUP BY lt.id
ORDER BY boxes DESC, lt.position
`

type UserLabelTypeCountsRow struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
	Boxes int64  `json:"boxes"`
}

func (q *Queries) UserLabelTypeCounts(ctx context.Context, userID uuid.UUID) ([]UserLabelTypeCountsRow, error) {
	rows, err := q.db.Query(ctx, userLabelTypeCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserLabelTypeCountsRow
	for rows.Next() {
		var i UserLabelTypeCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Boxes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
