// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracking.sql

package db

import (
	"context"
)

const deleteTrackIfEmpty = `-- name: DeleteTrackIfEmpty :execrows
DELETE FROM tracks t
WHERE t.id = $1 AND NOT EXISTS (SELECT 1 FROM annotations a WHERE a.track_id = t.id)
`

func (q *Queries) DeleteTrackIfEmpty(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrackIfEmpty, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTrackProposalsFrom = `-- name: DeleteTrackProposalsFrom :exec
DELETE FROM annotations a
USING frames f
WHERE f.id = a.frame_id
    AND a.track_id = $1
    AND a.status = 'proposed'
    AND f.idx >= $2
`

type DeleteTrackProposalsFromParams struct {
	TrackID int64 `json:"track_id"`
	FromIdx int32 `json:"from_idx"`
}

// Clears what an earlier run proposed on frames the new run covers.
func (q *Queries) DeleteTrackProposalsFrom(ctx context.Context, arg DeleteTrackProposalsFromParams) error {
	_, err := q.db.Exec(ctx, deleteTrackProposalsFrom, arg.TrackID, arg.FromIdx)
	return err
}

const listFramesFrom = `-- name: ListFramesFrom :many
SELECT id, video_id, clip_id, idx, phash, status, status_by, status_at FROM frames WHERE clip_id = $1 AND idx >= $2 ORDER BY idx
`

type ListFramesFromParams struct {
	ClipID int64 `json:"clip_id"`
	Idx    int32 `json:"idx"`
}

func (q *Queries) ListFramesFrom(ctx context.Context, arg ListFramesFromParams) ([]Frame, error) {
	rows, err := q.db.Query(ctx, listFramesFrom, arg.ClipID, arg.Idx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Frame
	for rows.Next() {
		var i Frame
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ClipID,
			&i.Idx,
			&i.Phash,
			&i.Status,
			&i.StatusBy,
			&i.StatusAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProposals = `-- name: UpsertProposals :execrows
INSERT INTO annotations (track_id, frame_id, x, y, width, height, source, status, model_version)
SELECT
    $1,
    unnest($2::bigint[]),
    unnest($3::float8[]),
    unnest($4::float8[]),
    unnest($5::float8[]),
    unnest($6::float8[]),
    $7,
    'proposed',
    $8
ON CONFLICT (track_id, frame_id) DO UPDATE SET
    x = excluded.x,
    y = excluded.y,
    width = excluded.width,
    height = excluded.height,
    source = excluded.source,
    model_version = excluded.model_version,
    updated_at = now()
WHERE annotations.status = 'proposed'
`

type UpsertProposalsParams struct {
	TrackID      int64     `json:"track_id"`
	FrameIds     []int64   `json:"frame_ids"`
	Xs           []float64 `json:"xs"`
	Ys           []float64 `json:"ys"`
	Widths       []float64 `json:"widths"`
	Heights      []float64 `json:"heights"`
	Source       string    `json:"source"`
	ModelVersion string    `json:"model_version"`
}

// Only proposals are replaced. Boxes a labeler drew, accepted, or rejected stay.
func (q *Queries) UpsertProposals(ctx context.Context, arg UpsertProposalsParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertProposals,
		arg.TrackID,
		arg.FrameIds,
		arg.Xs,
		arg.Ys,
		arg.Widths,
		arg.Heights,
		arg.Source,
		arg.ModelVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
