// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClips = `-- name: CountClips :one
SELECT count(*)::int FROM clips WHERE video_id = $1
`

func (q *Queries) CountClips(ctx context.Context, videoID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countClips, videoID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createClip = `-- name: CreateClip :one
INSERT INTO clips (video_id, idx, start_frame, frame_count)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateClipParams struct {
	VideoID    int64 `json:"video_id"`
	Idx        int32 `json:"idx"`
	StartFrame int32 `json:"start_frame"`
	FrameCount int32 `json:"frame_count"`
}

func (q *Queries) CreateClip(ctx context.Context, arg CreateClipParams) (int64, error) {
	row := q.db.QueryRow(ctx, createClip,
		arg.VideoID,
		arg.Idx,
		arg.StartFrame,
		arg.FrameCount,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (name, filename, extract_fps)
VALUES ($1, $2, $3)
RETURNING id, name, filename, notes, status, error, ingest_progress, split, extract_fps, width, height, fps, duration_ms, frame_count, created_at
`

type CreateVideoParams struct {
	Name       string  `json:"name"`
	Filename   string  `json:"filename"`
	ExtractFps float64 `json:"extract_fps"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo, arg.Name, arg.Filename, arg.ExtractFps)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Filename,
		&i.Notes,
		&i.Status,
		&i.Error,
		&i.IngestProgress,
		&i.Split,
		&i.ExtractFps,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.DurationMs,
		&i.FrameCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClips = `-- name: DeleteClips :exec
DELETE FROM clips WHERE video_id = $1
`

func (q *Queries) DeleteClips(ctx context.Context, videoID int64) error {
	_, err := q.db.Exec(ctx, deleteClips, videoID)
	return err
}

const deleteVideo = `-- name: DeleteVideo :execrows
DELETE FROM videos WHERE id = $1
`

func (q *Queries) DeleteVideo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVideo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failIngest = `-- name: FailIngest :exec
UPDATE videos SET status = 'failed', error = $2 WHERE id = $1
`

type FailIngestParams struct {
	ID    int64  `json:"id"`
	Error string `json:"error"`
}

func (q *Queries) FailIngest(ctx context.Context, arg FailIngestParams) error {
	_, err := q.db.Exec(ctx, failIngest, arg.ID, arg.Error)
	return err
}

const failInterruptedIngests = `-- name: FailInterruptedIngests :execrows
UPDATE videos SET status = 'failed', error = 'Ingest was interrupted by an API restart.'
WHERE status = 'processing'
`

func (q *Queries) FailInterruptedIngests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, failInterruptedIngests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishIngest = `-- name: FinishIngest :exec
UPDATE videos SET status = 'ready', ingest_progress = 1, frame_count = $2
WHERE id = $1
`

type FinishIngestParams struct {
	ID         int64 `json:"id"`
	FrameCount int32 `json:"frame_count"`
}

func (q *Queries) FinishIngest(ctx context.Context, arg FinishIngestParams) error {
	_, err := q.db.Exec(ctx, finishIngest, arg.ID, arg.FrameCount)
	return err
}

const getVideo = `-- name: GetVideo :one
SELECT id, name, filename, notes, status, error, ingest_progress, split, extract_fps, width, height, fps, duration_ms, frame_count, created_at FROM videos WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Filename,
		&i.Notes,
		&i.Status,
		&i.Error,
		&i.IngestProgress,
		&i.Split,
		&i.ExtractFps,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.DurationMs,
		&i.FrameCount,
		&i.CreatedAt,
	)
	return i, err
}

type InsertFramesParams struct {
	VideoID int64 `json:"video_id"`
	ClipID  int64 `json:"clip_id"`
	Idx     int32 `json:"idx"`
	Phash   int64 `json:"phash"`
}

const listClips = `-- name: ListClips :many
SELECT id, video_id, idx, start_frame, frame_count FROM clips WHERE video_id = $1 ORDER BY idx
`

func (q *Queries) ListClips(ctx context.Context, videoID int64) ([]Clip, error) {
	rows, err := q.db.Query(ctx, listClips, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Clip
	for rows.Next() {
		var i Clip
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Idx,
			&i.StartFrame,
			&i.FrameCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideos = `-- name: ListVideos :many
SELECT
    v.id, v.name, v.filename, v.notes, v.status, v.error, v.ingest_progress, v.split, v.extract_fps, v.width, v.height, v.fps, v.duration_ms, v.frame_count, v.created_at,
    (SELECT count(*) FROM clips c WHERE c.video_id = v.id)::int AS clip_count
FROM videos v
ORDER BY v.created_at DESC, v.id DESC
`

type ListVideosRow struct {
	Video     Video `json:"video"`
	ClipCount int32 `json:"clip_count"`
}

func (q *Queries) ListVideos(ctx context.Context) ([]ListVideosRow, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVideosRow
	for rows.Next() {
		var i ListVideosRow
		if err := rows.Scan(
			&i.Video.ID,
			&i.Video.Name,
			&i.Video.Filename,
			&i.Video.Notes,
			&i.Video.Status,
			&i.Video.Error,
			&i.Video.IngestProgress,
			&i.Video.Split,
			&i.Video.ExtractFps,
			&i.Video.Width,
			&i.Video.Height,
			&i.Video.Fps,
			&i.Video.DurationMs,
			&i.Video.FrameCount,
			&i.Video.CreatedAt,
			&i.ClipCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueIngest = `-- name: QueueIngest :one
UPDATE videos SET status = 'queued', error = '', ingest_progress = 0
WHERE id = $1 AND status IN ('uploading', 'failed')
RETURNING id, name, filename, notes, status, error, ingest_progress, split, extract_fps, width, height, fps, duration_ms, frame_count, created_at
`

func (q *Queries) QueueIngest(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRow(ctx, queueIngest, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Filename,
		&i.Notes,
		&i.Status,
		&i.Error,
		&i.IngestProgress,
		&i.Split,
		&i.ExtractFps,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.DurationMs,
		&i.FrameCount,
		&i.CreatedAt,
	)
	return i, err
}

const setIngestProgress = `-- name: SetIngestProgress :exec
UPDATE videos SET ingest_progress = $2 WHERE id = $1
`

type SetIngestProgressParams struct {
	ID             int64   `json:"id"`
	IngestProgress float32 `json:"ingest_progress"`
}

func (q *Queries) SetIngestProgress(ctx context.Context, arg SetIngestProgressParams) error {
	_, err := q.db.Exec(ctx, setIngestProgress, arg.ID, arg.IngestProgress)
	return err
}

const setVideoProbe = `-- name: SetVideoProbe :exec
UPDATE videos SET width = $2, height = $3, fps = $4, duration_ms = $5
WHERE id = $1
`

type SetVideoProbeParams struct {
	ID         int64   `json:"id"`
	Width      int32   `json:"width"`
	Height     int32   `json:"height"`
	Fps        float64 `json:"fps"`
	DurationMs int64   `json:"duration_ms"`
}

func (q *Queries) SetVideoProbe(ctx context.Context, arg SetVideoProbeParams) error {
	_, err := q.db.Exec(ctx, setVideoProbe,
		arg.ID,
		arg.Width,
		arg.Height,
		arg.Fps,
		arg.DurationMs,
	)
	return err
}

const startProcessing = `-- name: StartProcessing :execrows
UPDATE videos SET status = 'processing', error = '', ingest_progress = 0
WHERE id = $1
`

func (q *Queries) StartProcessing(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, startProcessing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVideo = `-- name: UpdateVideo :one
UPDATE videos SET
    name = coalesce($1, name),
    notes = coalesce($2, notes),
    split = coalesce($3, split)
WHERE id = $4
RETURNING id, name, filename, notes, status, error, ingest_progress, split, extract_fps, width, height, fps, duration_ms, frame_count, created_at
`

type UpdateVideoParams struct {
	Name  pgtype.Text `json:"name"`
	Notes pgtype.Text `json:"notes"`
	Split pgtype.Text `json:"split"`
	ID    int64       `json:"id"`
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideo,
		arg.Name,
		arg.Notes,
		arg.Split,
		arg.ID,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Filename,
		&i.Notes,
		&i.Status,
		&i.Error,
		&i.IngestProgress,
		&i.Split,
		&i.ExtractFps,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.DurationMs,
		&i.FrameCount,
		&i.CreatedAt,
	)
	return i, err
}
